name: daily-challenge

on:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

jobs:
  post-to-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run webhook POST
        env:
          DLC_WEBHOOK_URL: ${{ secrets.DLC_WEBHOOK_URL }}
          LEETCODE_CHANNEL_ID: ${{ secrets.LEETCODE_CHANNEL_ID }}
          SOLUTIONS_CHANNEL_ID: ${{ secrets.SOLUTIONS_CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python discord_webhook.py
